# Generated by Django 3.2.13 on 2022-08-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='investors',
            fields=[
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('investor_contact_no', models.BigIntegerField(blank=True, null=True)),
                ('investor_email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='startup_data',
            fields=[
                ('company_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, max_length=30, null=True)),
                ('founder', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('team', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='startup_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_files', models.FileField(blank=True, null=True, upload_to='mediafiles')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('like', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='startup_user',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
