# Generated by Django 3.0.8 on 2022-08-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furyapp', '0002_auto_20220813_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='investors',
            name='money',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup_data',
            name='funds',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
