# Generated by Django 3.0.8 on 2022-08-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furyapp', '0003_auto_20220814_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('companny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furyapp.startup_data')),
            ],
        ),
    ]
