# Generated by Django 3.0.8 on 2022-08-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furyapp', '0004_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
